### ISSUE TITLE
TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by SkylekFR** [KevinRohn/github-action-upload-play-store#1]
Hi,

Sometime I want to upload AAB on my application on open testing and i encounter timeouterror in python script.
I've checked on google cloud console metrics and the mean latency is around 1minutes

google.play.publishingapi.v3.BundlesService.Upload | 2 | 0 | 1 minute | 1 minute
-- | -- | -- | -- | --

StackTrace: 
`Run from google.oauth2.service_account import Credentials
Traceback (most recent call last):
  File "/home/runner/work/_temp/1224f28f-708e-4039-bbbd-f24ac3f37060.py", line 23, in <module>
    ).execute()
      ~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
                    ~~~~~~~~~~~~^
        self.resumable_uri, method="PUT", body=data, headers=headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
                        ~~~~~~~~~~~~~~~~~^
        uri,
        ^^^^
    ...<5 lines>...
        **kwargs
        ^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/httplib2/__init__.py", line 1727, in request
    (response, content) = self._request(
                          ~~~~~~~~~~~~~^
        conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/httplib2/__init__.py", line 1447, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/httplib2/__init__.py", line 1399, in _conn_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out`

**Comment by KevinRohn** [comment]
Could it be that you have a large bundle file (Or slow upload connection)? Since Google Cloud Console shows the upload takes around 1 minute, and you're hitting a timeout, I think we need to increase the default timeout from the used `httplib2` package to handle larger files.

**Comment by KevinRohn** [comment]
I fixed it, can you please try it out @SkylekFR ? #5

**Comment by SkylekFR** [comment]
Hi, thanks so much for the fix, 

As the bug was random depending of the size of .aab and occured only when I was deploying in production, I'll not be able to produce a 100% confidence test.

But I'll tell you about our next production release and how it went

**Comment by SkylekFR** [comment]
I'll try with a little timeout like 20s and then increase it so see if it's about it

**Comment by KevinRohn** [comment]
@SkylekFR Thank you -  let me know how it goes.

**Comment by megajogos** [comment]
@KevinRohn Unfortunately, the fix did not resolve the timeout error. Log:

```
Warning: Unexpected input(s) 'timeout', valid inputs are ['service_account_json', 'package_name', 'aab_file_path', 'track', 'release_status']
Run KevinRohn/github-action-upload-play-store@v***.0.2
  with:
    service_account_json: ***
    package_name: air.br.com.cardgames.mobile
    aab_file_path: build/Android/cardgames.aab
    track: internal
    release_status: completed
    timeout: 600
```
It seems like the "timeout" param does not exist.

Complete log:

```
Run KevinRohn/github-action-upload-play-store@v***.0.2
  with:
    service_account_json: ***
    package_name: air.br.com.cardgames.mobile
    aab_file_path: build/Android/cardgames.aab
    track: internal
    release_status: completed
    timeout: 600
  env:
    APP_ID: cardgames
    BUILD_ENV: prod
    VERSION_NAME: ***46.***.***99
    VERSION_CODE: ***46***00***99
    OUTPUT_PATH: build/Android/cardgames.aab
    TARGET_ARCHS: armv7,arm64
Run actions/setup-python@v5
Installed versions
Run valid_tracks=("internal" "alpha" "beta" "production" "rollout")
Run pip install --upgrade packaging google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
Collecting packaging
  Downloading packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting google-auth
  Downloading google_auth-2.52.0-py3-none-any.whl.metadata (5.5 kB)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-***.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-python-client
  Downloading google_api_python_client-2.***96.0-py3-none-any.whl.metadata (7.0 kB)
Collecting pyasn***-modules>=0.2.*** (from google-auth)
  Downloading pyasn***_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth)
  Downloading cryptography-48.0.0-cp3***-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (*** kB)
Collecting httplib2<***.0.0,>=0.***9.0 (from google-auth-httplib2)
  Downloading httplib2-0.3***.2-py3-none-any.whl.metadata (2.2 kB)
Collecting pyparsing<4,>=3.*** (from httplib2<***.0.0,>=0.***9.0->google-auth-httplib2)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5 (from google-api-python-client)
  Downloading google_api_core-2.30.3-py3-none-any.whl.metadata (3.*** kB)
Collecting uritemplate<5,>=3.0.*** (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=***.63.2 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading googleapis_common_protos-***.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting protobuf<8.0.0,>=4.25.8 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading protobuf-7.34.***-cp3***0-abi3-manylinux20***4_x86_64.whl.metadata (595 bytes)
Collecting proto-plus<2.0.0,>=***.22.3 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading proto_plus-***.28.0-py3-none-any.whl.metadata (2.2 kB)
Collecting requests<3.0.0,>=2.20.0 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading requests-2.33.***-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading charset_normalizer-3.4.7-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading idna-3.***4-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=***.26 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth)
  Downloading cffi-2.0.0-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pyasn***<0.7.0,>=0.6.*** (from pyasn***-modules>=0.2.***->google-auth)
  Downloading pyasn***-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Downloading oauthlib-3.3.***-py3-none-any.whl.metadata (7.9 kB)
Downloading packaging-26.2-py3-none-any.whl (***00 kB)
Downloading google_auth-2.52.0-py3-none-any.whl (245 kB)
Downloading google_auth_oauthlib-***.4.0-py3-none-any.whl (***9 kB)
Downloading google_auth_httplib2-0.4.0-py3-none-any.whl (9.5 kB)
Downloading httplib2-0.3***.2-py3-none-any.whl (9*** kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (***22 kB)
Downloading google_api_python_client-2.***96.0-py3-none-any.whl (***5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ***5.2/***5.2 MB 259.8 MB/s  0:00:00
Downloading google_api_core-2.30.3-py3-none-any.whl (***73 kB)
Downloading googleapis_common_protos-***.75.0-py3-none-any.whl (300 kB)
Downloading proto_plus-***.28.0-py3-none-any.whl (50 kB)
Downloading protobuf-7.34.***-cp3***0-abi3-manylinux20***4_x86_64.whl (324 kB)
Downloading requests-2.33.***-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.manylinux_2_28_x86_64.whl (2***5 kB)
Downloading idna-3.***4-py3-none-any.whl (72 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (*** kB)
Downloading urllib3-2.7.0-py3-none-any.whl (***3*** kB)
Downloading certifi-2026.4.22-py3-none-any.whl (***35 kB)
Downloading cryptography-48.0.0-cp3***-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 286.0 MB/s  0:00:00
Downloading cffi-2.0.0-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.whl (2***9 kB)
Downloading pyasn***_modules-0.4.2-py3-none-any.whl (***8*** kB)
Downloading pyasn***-0.6.3-py3-none-any.whl (83 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.***-py3-none-any.whl (***60 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: urllib3, uritemplate, pyparsing, pycparser, pyasn***, protobuf, packaging, oauthlib, idna, charset_normalizer, certifi, requests, pyasn***-modules, proto-plus, httplib2, googleapis-common-protos, cffi, requests-oauthlib, cryptography, google-auth, google-auth-oauthlib, google-auth-httplib2, google-api-core, google-api-python-client

Successfully installed certifi-2026.4.22 cffi-2.0.0 charset_normalizer-3.4.7 cryptography-48.0.0 google-api-core-2.30.3 google-api-python-client-2.***96.0 google-auth-2.52.0 google-auth-httplib2-0.4.0 google-auth-oauthlib-***.4.0 googleapis-common-protos-***.75.0 httplib2-0.3***.2 idna-3.***4 oauthlib-3.3.*** packaging-26.2 proto-plus-***.28.0 protobuf-7.34.*** pyasn***-0.6.3 pyasn***-modules-0.4.2 pycparser-3.0 pyparsing-3.3.2 requests-2.33.*** requests-oauthlib-2.0.0 uritemplate-4.2.0 urllib3-2.7.0
Run echo "***
Run from google.oauth2.service_account import Credentials
Traceback (most recent call last):
  File "/home/runner/work/_temp/c330480e-40d***-4772-950d-96453b***b656.py", line 23, in <module>
    ).execute()
      ~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/googleapiclient/_helpers.py", line ***30, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/googleapiclient/_helpers.py", line ***30, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/googleapiclient/http.py", line ***084, in next_chunk
    resp, content = http.request(
                    ~~~~~~~~~~~~^
        self.resumable_uri, method="PUT", body=data, headers=headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/google_auth_httplib2.py", line 2***4, in request
    response, content = self.http.request(
                        ~~~~~~~~~~~~~~~~~^
        uri,
        ^^^^
    ...<5 lines>...
        **kwargs
        ^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/httplib2/__init__.py", line ***727, in request
    (response, content) = self._request(
                          ~~~~~~~~~~~~~^
        conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/httplib2/__init__.py", line ***447, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/site-packages/httplib2/__init__.py", line ***399, in _conn_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/http/client.py", line ***459, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/http/client.py", line 336, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/http/client.py", line 297, in _read_status
    line = str(self.fp.readline(_MAXLINE + ***), "iso-8859-***")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/socket.py", line 729, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/ssl.py", line ***304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.***4.5/x64/lib/python3.***4/ssl.py", line ***38, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out```

**Comment by KevinRohn** [comment]
@megajogos can you please test it by using:

`KevinRohn/github-action-upload-play-store@fix-timeout`

?

**Comment by megajogos** [comment]
@KevinRohn 

Using KevinRohn/github-action-upload-play-store@fix-timeout we have the following error:

```
Run KevinRohn/github-action-upload-play-store@fix-timeout
Run actions/setup-python@v5
Installed versions
Run valid_tracks=("internal" "alpha" "beta" "production" "rollout")
Run pip install --upgrade packaging google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
Collecting packaging
  Downloading packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting google-auth
  Downloading google_auth-2.52.0-py3-none-any.whl.metadata (5.5 kB)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-***.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-python-client
  Downloading google_api_python_client-2.***96.0-py3-none-any.whl.metadata (7.0 kB)
Collecting pyasn***-modules>=0.2.*** (from google-auth)
  Downloading pyasn***_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth)
  Downloading cryptography-48.0.0-cp3***-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (*** kB)
Collecting httplib2<***.0.0,>=0.***9.0 (from google-auth-httplib2)
  Downloading httplib2-0.3***.2-py3-none-any.whl.metadata (2.2 kB)
Collecting pyparsing<4,>=3.*** (from httplib2<***.0.0,>=0.***9.0->google-auth-httplib2)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5 (from google-api-python-client)
  Downloading google_api_core-2.30.3-py3-none-any.whl.metadata (3.*** kB)
Collecting uritemplate<5,>=3.0.*** (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=***.63.2 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading googleapis_common_protos-***.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting protobuf<8.0.0,>=4.25.8 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading protobuf-7.34.***-cp3***0-abi3-manylinux20***4_x86_64.whl.metadata (595 bytes)
Collecting proto-plus<2.0.0,>=***.22.3 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading proto_plus-***.28.0-py3-none-any.whl.metadata (2.2 kB)
Collecting requests<3.0.0,>=2.20.0 (from google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading requests-2.34.0-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading charset_normalizer-3.4.7-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading idna-3.***4-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=***.26 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.***.*,!=2.2.*,!=2.3.0,<3.0.0,>=***.3***.5->google-api-python-client)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth)
  Downloading cffi-2.0.0-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pyasn***<0.7.0,>=0.6.*** (from pyasn***-modules>=0.2.***->google-auth)
  Downloading pyasn***-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Downloading oauthlib-3.3.***-py3-none-any.whl.metadata (7.9 kB)
Downloading packaging-26.2-py3-none-any.whl (***00 kB)
Downloading google_auth-2.52.0-py3-none-any.whl (245 kB)
Downloading google_auth_oauthlib-***.4.0-py3-none-any.whl (***9 kB)
Downloading google_auth_httplib2-0.4.0-py3-none-any.whl (9.5 kB)
Downloading httplib2-0.3***.2-py3-none-any.whl (9*** kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (***22 kB)
Downloading google_api_python_client-2.***96.0-py3-none-any.whl (***5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ***5.2/***5.2 MB 87.8 MB/s  0:00:00
Downloading google_api_core-2.30.3-py3-none-any.whl (***73 kB)
Downloading googleapis_common_protos-***.75.0-py3-none-any.whl (300 kB)
Downloading proto_plus-***.28.0-py3-none-any.whl (50 kB)
Downloading protobuf-7.34.***-cp3***0-abi3-manylinux20***4_x86_64.whl (324 kB)
Downloading requests-2.34.0-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.manylinux_2_28_x86_64.whl (2***5 kB)
Downloading idna-3.***4-py3-none-any.whl (72 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (*** kB)
Downloading urllib3-2.7.0-py3-none-any.whl (***3*** kB)
Downloading certifi-2026.4.22-py3-none-any.whl (***35 kB)
Downloading cryptography-48.0.0-cp3***-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 334.9 MB/s  0:00:00
Downloading cffi-2.0.0-cp3***4-cp3***4-manylinux20***4_x86_64.manylinux_2_***7_x86_64.whl (2***9 kB)
Downloading pyasn***_modules-0.4.2-py3-none-any.whl (***8*** kB)
Downloading pyasn***-0.6.3-py3-none-any.whl (83 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.***-py3-none-any.whl (***60 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: urllib3, uritemplate, pyparsing, pycparser, pyasn***, protobuf, packaging, oauthlib, idna, charset_normalizer, certifi, requests, pyasn***-modules, proto-plus, httplib2, googleapis-common-protos, cffi, requests-oauthlib, cryptography, google-auth, google-auth-oauthlib, google-auth-httplib2, google-api-core, google-api-python-client

Successfully installed certifi-2026.4.22 cffi-2.0.0 charset_normalizer-3.4.7 cryptography-48.0.0 google-api-core-2.30.3 google-api-python-client-2.***96.0 google-auth-2.52.0 google-auth-httplib2-0.4.0 google-auth-oauthlib-***.4.0 googleapis-common-protos-***.75.0 httplib2-0.3***.2 idna-3.***4 oauthlib-3.3.*** packaging-26.2 proto-plus-***.28.0 protobuf-7.34.*** pyasn***-0.6.3 pyasn***-modules-0.4.2 pycparser-3.0 pyparsing-3.3.2 requests-2.34.0 requests-oauthlib-2.0.0 uritemplate-4.2.0 urllib3-2.7.0
Run echo "***
Run from google.oauth2.service_account import Credentials
Traceback (most recent call last):
  File "/home/runner/work/_temp/06a88a44-5a69-4b3***-b***f8-b8f46cf28f8a.py", line ***2, in <module>
    authorized_http = credentials.authorize(http)
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'authorize'
Error: Process completed with exit code ***.
```
